### ISSUE TITLE
AttributeError: 'AvalancheDataset' object has no attribute 'targets_task_labels'

### ISSUE THREAD

**Issue by wudibaolongshi** [VerwimpEli/CLAD#1]
when i run detection_avalanche.py, the error occurs,which is located as following in avalanche\benchmarks\scenarios\deprecated\dataset_scenario.py:

# Extract task labels from the dataset
            exp_dataset: AvalancheDataset
            for i, exp_dataset in enumerate(exp_data):  # type: ignore
                task_labels_list.append(
                    set(exp_dataset.targets_task_labels)
                )  # type: ignore
AvalancheDataset has no attribute ".targets_task_labels". How can i solve it

**Comment by VerwimpEli** [comment]
There seems to be some breaking changes with the latest versions of Avalanche. I tested now with version 0.2.0, which seems to work. I updated the readme. At first glance, it seems to be a bug in Avalanche itself, I'll try to come back at it in the future.

Can you test whether verison 0.2.0 of Avalanche works for you?

**Comment by wudibaolongshi** [comment]
> There seems to be some breaking changes with the latest versions of Avalanche. I tested now with version 0.2.0, which seems to work. I updated the readme. At first glance, it seems to be a bug in Avalanche itself, I'll try to come back at it in the future.
> 
> Can you test whether verison 0.2.0 of Avalanche works for you?

it is usefull! Thanks!!!♥
